<?php

namespace App\Services;

use App\Models\AiGeneration;
use App\Models\AutomationTestResult;
use App\Models\Bugreport;
use App\Models\Checklist;
use App\Models\DesignLink;
use App\Models\Documentation;
use App\Models\Note;
use App\Models\ProjectFeature;
use App\Models\Release;
use App\Models\TestRun;
use App\Models\TestSuite;
use App\Models\TestUser;

class SectionConfigRegistry
{
    /**
     * Return all section configurations indexed by section key.
     *
     * @return array<string, array{key: string, title: string, description: string, features: list<string>, model?: class-string<\Illuminate\Database\Eloquent\Model>}>
     */
    public function all(): array
    {
        return [
            'checklists' => [
                'key' => 'checklists',
                'title' => 'Checklists',
                'description' => 'Flexible tabular checklists with customizable columns for tracking any structured data across projects.',
                'features' => [
                    'Custom column types: text, checkbox, select with colors, date',
                    'CSV import with smart column mapping and export with UTF-8 BOM',
                    'Export selected (checked) rows only via File dropdown',
                    'Section headers with custom background/font colors and font weight',
                    'Drag-and-drop row and column reordering',
                    'Dynamic filters by select columns and date range',
                    'Toggle column visibility with localStorage persistence',
                    'Resizable columns with mouse drag',
                    'Multiple note drafts per checklist with auto-save to localStorage',
                    'Import notes by splitting on line breaks into rows',
                    'Clone new checklists from existing templates',
                    'Bulk add multiple rows, add above/below current row',
                    'Undo last save functionality',
                    'Progressive rendering with Load More / Show All',
                    'Full-text search with result highlighting',
                    'Copy link to clipboard',
                    'Drag-and-drop card reordering on index page',
                    'Category grouping with collapsible sections',
                    'Inline category rename from section header',
                    'Import notes into specific section by header',
                    'Copy selected rows to another checklist',
                    'Cross-project row clipboard with smart column mapping',
                    'Bulk actions: create bug report with auto-link back to checklist row',
                    'Bulk actions: create test case with auto-link back to checklist rows',
                    'Bulk actions: create test run from selected rows',
                    'Feature linking per checklist with inline quick-create',
                    'Filter checklists by linked feature on index page',
                    'Deferred rows loading with skeleton placeholder for fast initial render',
                    'Module tagging on checklists and individual rows (UI, API, Backend, Database, Integration)',
                    'Filter rows by module in the filter panel',
                    'AI-powered translation for import notes via TranslateButtons',
                    'Smart row count excluding empty rows and section headers on index page',
                    'Delta saves: PATCH only changed rows instead of full PUT for cell edits with debounced auto-save',
                    'Ctrl+C/V keyboard shortcuts for copying and pasting rows with cursor-aware insert position',
                    'Row selection by clicking row numbers with Shift+Click range, Ctrl+A select all, and Esc to clear',
                    'Arrow keys and Tab/Shift+Tab navigation between table cells',
                    'Sticky header shadow on scroll for visual depth',
                    'Clear status per select column in bulk Change Status action',
                    'Infinite scroll auto-loading rows on scroll while search and filters work across all rows',
                    'Rich text editing in cells: bold, italic, strikethrough, and color formatting via inline toolbar',
                ],
                'model' => Checklist::class,
            ],
            'test-suites' => [
                'key' => 'test-suites',
                'title' => 'Test Suites',
                'description' => 'Hierarchical test case organization and management for structured QA workflows with full traceability.',
                'features' => [
                    'Parent/child suite hierarchy with nested views',
                    '9 test case types: functional, smoke, regression, integration, acceptance, performance, security, usability, other',
                    'Priority levels: low, medium, high, critical',
                    'Severity levels: trivial, minor, major, critical, blocker',
                    'Automation status tracking: not automated, to be automated, automated',
                    'Step-by-step test steps with expected results per step',
                    'Preconditions and expected result fields',
                    'Module tagging per suite and test case (UI, API, Backend, Database, Integration)',
                    'Tags for categorization',
                    'Creator tracking and filtering by user',
                    'File attachments per test case (images, PDFs, documents, up to 10 MB)',
                    'Notes per test case',
                    'Drag-and-drop reordering within and across suites',
                    'Full-text search with result highlighting',
                    'Color-coded type badges with icons',
                    'Copy link to clipboard',
                    'Feature linking per test case with inline quick-create',
                    'Filter test cases by linked feature on index page',
                    'Feature linking per test suite with inline quick-create',
                    'Cross-project bulk copy with attachments, features, and notes',
                    'Bulk group selected test cases into new subcategory',
                    'CSV export of all or selected test cases with UTF-8 BOM support',
                    'Import test cases from CSV/Excel with auto field mapping and alias support',
                    'AI-powered translation for quick-add steps via TranslateButtons',
                    'Create note with quick-add dialog from test suite page',
                    'Bot icon indicator for automated test cases on index and suite pages',
                    'Feature badges displayed on test cases in suite view',
                ],
                'model' => TestSuite::class,
            ],
            'test-runs' => [
                'key' => 'test-runs',
                'title' => 'Test Runs',
                'description' => 'Execute and track test case results with detailed progress monitoring, assignments, and external integrations.',
                'features' => [
                    'Create runs from selected test cases across suites',
                    'Status tracking per case: untested, passed, failed, blocked, skipped, retest',
                    'Visual progress bar with percentage and per-status statistics',
                    'Quick status buttons for rapid result entry',
                    'Bulk update status and assignments for multiple cases',
                    'Assign cases to users, assign-to-me shortcut',
                    'Actual result notes and time spent per case',
                    'External links: ClickUp and Qase integration per case',
                    'Environment and milestone metadata',
                    'Run lifecycle: active, completed, archived',
                    'Track started, completed timestamps and completed-by user',
                    'Pause/resume timer to exclude breaks from elapsed time',
                    'Live elapsed time display with automatic ticking for active runs',
                    'Creator tracking per test run',
                    'Group test cases by suite with section headers',
                    'Filter by status and assigned user',
                    'Full-text search with result highlighting',
                    'Copy link to clipboard',
                    'Create runs from selected checklist rows (each row becomes a check item)',
                    'Comprehensive filter panel: status, source, environment, author, date ranges, stat ranges',
                    'Add cases to active test run without recreating (skips duplicates)',
                    'Source picker dropdown: create new run from test cases or checklist',
                    'Remove individual cases from active test runs with confirmation dialog',
                    'Select All / Deselect All toggle for test cases and checklist rows',
                    'Show expected result for checklist-based checks on expand',
                    'Create bug report directly from any check with pre-filled fields',
                    'Manual time adjustment: click elapsed time to add hours/minutes to total',
                    'Search test cases by name when creating runs or adding cases',
                    'Source indicator with dropdown links to originating test suites or checklist',
                    'Rich text title rendering for checklist-based test run items',
                ],
                'model' => TestRun::class,
            ],
            'bugreports' => [
                'key' => 'bugreports',
                'title' => 'Bug Reports',
                'description' => 'Comprehensive issue tracking and bug management with full lifecycle, triage levels, and file attachments.',
                'features' => [
                    'Status workflow: to do, in progress, in review, needs changes, cancelled, done',
                    'Severity levels: critical, major, minor, trivial',
                    'Priority levels: high, medium, low',
                    'Steps to reproduce with expected and actual results',
                    'Environment field for test environment details',
                    'Reporter and assignee tracking per bug',
                    'File attachments with image preview gallery (up to 10 MB)',
                    'Download links with file size display',
                    'Color-coded severity and priority badges',
                    'Full-text search by title and description with highlighting',
                    'Filters by status, priority, severity, author, created/updated date ranges',
                    'Create from selected checklist rows with auto-link back',
                    'Copy link to clipboard',
                    'Feature linking per bug report with inline quick-create',
                    'Fixed-on environment tracking (develop, staging, production)',
                    'Auto-save draft to localStorage with restore on return',
                    'ClickUp integration: export bug reports, sync statuses via webhook',
                ],
                'model' => Bugreport::class,
            ],
            'design' => [
                'key' => 'design',
                'title' => 'Design',
                'description' => 'Centralized hub for design resource links — Figma files, prototypes, brand guidelines, and external tools.',
                'features' => [
                    'Quick links grid with colored icon cards',
                    'Support for Figma, Zeplin, InVision, PDF, and custom URLs',
                    'Category grouping: Figma, Mockups, Assets, Guidelines',
                    'Inline add, edit, and delete via dialogs',
                    'Full-text search by title, description, URL, and category',
                    'Copy link to clipboard',
                    'Open in new tab with external link indicator',
                    'Creator tracking per link',
                    'Filter by category and created date range with collapsible filter panel',
                ],
                'model' => DesignLink::class,
            ],
            'automation' => [
                'key' => 'automation',
                'title' => 'Automation',
                'description' => 'Playwright integration for automated test execution, discovery, and result tracking with tags and environments.',
                'features' => [
                    'Configure path to existing Playwright test projects',
                    'Auto-discover test files from tests/ and e2e/ directories',
                    'Parse test.describe() and test() blocks with @tag extraction',
                    'Support for .spec.js, .spec.ts, .test.js, .test.ts files',
                    'Link Playwright tests to CheckMate test cases',
                    'Run Playwright tests directly from CheckMate UI',
                    'Import JSON test results with pass/fail/skip/timeout statuses',
                    'Track error messages, stack traces, and execution times',
                    'Latest run statistics dashboard with pass rate',
                    'Results history with environment and tag display',
                    'Test environments with base URL, browser, workers, retries, and custom variables',
                    'Run templates: saved test profiles with environment, tags, and file patterns',
                    'Tag-based filtering with OR/AND mode for targeted test execution',
                    'One-click run from templates with pre-configured settings',
                ],
                'model' => AutomationTestResult::class,
            ],
            'releases' => [
                'key' => 'releases',
                'title' => 'Releases',
                'description' => 'Plan, track, and manage product releases with go/no-go decisions, feature tracking, quality checklists, and metrics.',
                'features' => [
                    'Release lifecycle: planning, development, testing, staging, ready, released',
                    'Go/no-go decision workflow with conditional approvals',
                    'Health indicators: green, yellow, red based on metrics',
                    'Feature tracking with test coverage percentages',
                    'Quality checklist with 5 categories: testing, security, performance, deployment, documentation',
                    'Blocker identification and tracking',
                    'Metrics snapshots with test completion and pass rates',
                    'Release readiness score with weighted breakdown',
                    'Blockers & risks dashboard with security status',
                    'Quality comparison vs previous release',
                    'Link test runs to releases for regression tracking',
                    'Decision tab with auto-recommendation from metrics',
                    'Planned vs actual release date tracking',
                    'Release-level notes and metadata',
                    'Releases section on project dashboard with latest 5 releases',
                    'Feature-scoped bug metrics instead of project-wide timeframe filtering',
                    'Filter releases by planned and actual date ranges',
                ],
                'model' => Release::class,
            ],
            'test-coverage' => [
                'key' => 'test-coverage',
                'title' => 'Test Coverage',
                'description' => 'AI-powered test coverage analytics with gap detection, intelligent recommendations, and coverage trend tracking.',
                'features' => [
                    'Overall coverage percentage with per-module breakdown',
                    'Project feature management with module and category grouping',
                    'Feature-to-test-case linking for coverage tracking',
                    'Auto-matching of test cases to features by title keywords',
                    'Manual test case linking dialog with search and toggle',
                    'AI-powered coverage analysis using Claude API',
                    'Automated coverage gap detection and prioritization',
                    'AI-generated test case suggestions for uncovered features',
                    'Coverage by category: functional, UI, API, security, performance',
                    'Risk assessment with impact analysis and recommendations',
                    'Coverage history tracking with trend visualization',
                    'Search and filter project features',
                    'Priority-based feature organization: critical, high, medium, low',
                    'Checklist coverage tracking alongside test cases',
                    'Separate link dialogs for test cases and checklists',
                    'Multi-module assignment for cross-cutting features',
                    'Module-aware checklist counting in coverage breakdown',
                    'Select All / Deselect All toggle in feature selector',
                ],
                'model' => ProjectFeature::class,
            ],
            'ai-generator' => [
                'key' => 'ai-generator',
                'title' => 'AI Generator',
                'description' => 'AI-powered test case generation from documentation, files, or screenshots with review workflow and direct import to test suites.',
                'features' => [
                    'Generate test cases from pasted text documentation or requirements',
                    'Generate test cases from uploaded TXT and Markdown files',
                    'Generate test cases from uploaded screenshot images',
                    'Multi-provider support: Google Gemini and Anthropic Claude',
                    'Configurable number of test cases per generation (1-20)',
                    'Client-side review and approval flow before import',
                    'Inline editing of generated test cases before import',
                    'Approve all / reject all bulk actions',
                    'Import approved test cases into existing or new test suites',
                    'Steps automatically converted to structured test step format',
                    'Priority and type assignment per generated test case',
                    'Generation usage tracking and analytics',
                    'Persist AI provider selection to localStorage',
                ],
                'model' => AiGeneration::class,
            ],
            'test-data' => [
                'key' => 'test-data',
                'title' => 'Test Data',
                'description' => 'Centralized management of test credentials, user accounts, payment methods, commands, and reference links for QA testing across environments.',
                'features' => [
                    'Test user accounts with name, email, and encrypted passwords',
                    'Role-based test user categorization (admin, user, moderator, tester)',
                    'Environment selection per entry: Develop, Staging, Production',
                    'Validity status tracking for active and expired test accounts',
                    'Additional info field for custom key-value metadata per user',
                    'Tag-based organization for test users and payment methods',
                    'Payment method management: card, crypto, bank, PayPal, and custom types',
                    'Type-specific credential fields with encrypted storage',
                    'Payment system tracking (Stripe, PayPal, Square, Braintree)',
                    'Copy-to-clipboard for emails, passwords, and credentials',
                    'Password visibility toggle with eye icon',
                    'CSV/Excel import and export across all tabs via File dropdown',
                    'Bulk selection and deletion for users, payments, commands, and links',
                    'Search and filter by validity, environment, role, and payment type',
                    'Creator tracking per test data entry',
                    'Drag-and-drop row reordering for all test data types',
                    'Drag-and-drop column reordering with localStorage persistence',
                    'Column resizing with localStorage persistence',
                    'Commands tab for storing deploy, database, testing, and build commands',
                    'Copy-to-clipboard for commands with monospace display',
                    'Category-based grouping and filtering for commands and links',
                    'Links tab for storing reference URLs with descriptions and comments',
                    'Clickable URLs with external link icon for opening in new tabs',
                    'Category autocomplete suggestions from existing entries',
                    'Toggle column visibility per tab with Cols dropdown and localStorage persistence',
                ],
                'model' => TestUser::class,
            ],
            'payout-monitor' => [
                'key' => 'payout-monitor',
                'title' => 'Payout Monitor',
                'description' => 'Real-time log analysis tool for payment transaction monitoring with structured parsing, anomaly detection, and visual data presentation.',
                'features' => [
                    'Paste raw log data for instant structured parsing',
                    'Fetch latest logs from configured endpoint',
                    'Group events by payout ID with timeline view',
                    'Structured sender/recipient data extraction from senderKyc and recipientKyc',
                    'B2B and B2C transaction type support',
                    'Credit party and debit party field extraction',
                    'Bank account, IBAN, and MSISDN display in recipient section',
                    'Color-coded sections: sender (blue), recipient (emerald), transfer (purple)',
                    'Anomaly detection: FX rate, IBAN-country mismatch, currency-country mismatch',
                    'Anomaly detection: cross-step data mismatches, missing responses, suspicious amounts',
                    'Anomaly preview in collapsed payout header',
                    'Collapsible event timeline with raw JSON payload viewer',
                    'Search payouts by ID and beneficiary name',
                    'Filter by status: completed, pending, error',
                    'Clear Results with filter reset',
                    'Summary badges: total payouts, events, anomalies',
                    'Persistent log data in localStorage per project',
                    'Copy values to clipboard with HTTP fallback',
                ],
            ],
            'documentations' => [
                'key' => 'documentations',
                'title' => 'Documentation',
                'description' => 'Nested knowledge base with rich content editing, hierarchical organization, and full attachment support.',
                'features' => [
                    'Multi-level hierarchy: parent, child, grandchild pages',
                    'Rich text editor with inline image uploads',
                    'Category tagging per page',
                    'Tree navigation sidebar with search',
                    'Drag-and-drop page reordering',
                    'File attachments: images with gallery, documents with download',
                    'Subcategories section with quick-add button',
                    'Breadcrumb navigation through hierarchy',
                    'Recursive search through all hierarchy levels',
                    'Content search highlighting within pages',
                    'Document tree sidebar on index page with search and filtering',
                    'Copy link to clipboard',
                    'Export documentation as JSON with recursive children',
                    'Import documentation from JSON file as subcategories',
                ],
                'model' => Documentation::class,
            ],
            'notes' => [
                'key' => 'notes',
                'title' => 'Notes',
                'description' => 'Quick draft notes with publish capability for rapid idea capture and seamless integration with other modules.',
                'features' => [
                    'Draft note creation with title and content',
                    'Publish drafts directly to documentation pages',
                    'Import notes into checklist rows by splitting on line breaks',
                    'Select target checklist and column for import',
                    'Link notes to documentation pages',
                    'Draft/published status badges',
                    'Auto-save drafts to localStorage with timestamps',
                    'Restore draft capability with preview',
                    'Per-project note organization',
                    'Card-based grid layout with content preview',
                    'Delete confirmation dialog',
                    'Copy link to clipboard',
                    'AI-powered translation for note content via TranslateButtons',
                    'Fully clickable note cards for quick editing',
                ],
                'model' => Note::class,
            ],
        ];
    }
}
